### ISSUE TITLE
DRC warning: "The current configuration does not include the library ''."

### ISSUE THREAD

**Issue by xobs** [gregdavill/KiBuzzard#104]
With the latest `main` version da33521870e1b51d625efb8dc190ef643dab437f, each instance of kibuzzard generates a DRC failure:

![image](https://github.com/gregdavill/KiBuzzard/assets/238325/2dc77cff-4860-40c0-a4b4-1819c744722e)

This is with a freshly-installed KiCad 7.0.2

**Comment by joseluislemus** [comment]
Same issue here. This is with KiCad 7.0.7 on MacOS Ventura.

**Comment by gregdavill** [comment]
This issue is mainly because the labels are generated, rather than coming from a library. IMO this doesn't matter especially since the labels are saved in KiCad project. But I understand the rationale behind the DRC check for this.

There are a few ways to fix this:
 - Manually mark each KiBuzzard label as excluded
 - Disabling that DRC check, or switch it to a warning
 - Extend KiBuzzard so that it saves each label into a global/project library.

I'm not sure it really makes sense to do the last item.
